//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisi
    {
        public int ID { get; set; }
        public string Adı { get; set; }
        public string Soyadı { get; set; }
        public string İkinci_Ad { get; set; }
        public int Şehir { get; set; }
        public string Telefon { get; set; }
    
        public virtual Sehir Sehir { get; set; }
    }
}
